### ISSUE TITLE
Not seing the discord server

### ISSUE THREAD

**Issue by WeaponizedLego** [HunterSandlin/CodingWithFriends#1]
Hey People.

I can't see the discord server on my list any longer. Was I kicked from it, or is the server shutdown?

**Comment by HunterSandlin** [comment]
I'm looking into that. I need to hear back from Aristrudel before I can do anything. I'll keep you updated.

**Comment by Csecsi85** [comment]
Hi man, I just got a message from the mods and they told me that the server went down for unknown reason.

**Comment by WeaponizedLego** [comment]
Well, that sucks. But glad to hear I wasn't kicked from the server :)
